check_pgactivity

Fix check_pgactivity to run with Perl 5.10.0

---

check_pgactivity

Use server_version_num when possible, fallback to server_version evaluation if not possible.

Add basic support for PostgreSQL 10

---

check_pgactivity

As asked in issue #44 
Commets are welcome.

Modify check_settings to handle pending_restart in 9.5+

---

check_pgactivity

First try at a sequences_exhausted probe. The purpose it to make sure there is no auto-incremented column that will fail in the close future in a database because it has either reached the maximum value of the sequence or the maximum value of the data type.

New sequences_exhausted probe

---

check_pgactivity

Total number was accounted incorrectly, the probe summed the maximum wait time.

Account total number of wait events correctly

---

check_pgactivity

Add check_pgdata_permissions

---

check_pgactivity

Specific tool didn't use for fetch latest version online.
_Curl_ didn't follow to redirect if option "--location" not set (http redirect to https).

Fix fetching method

---

check_pgactivity

This commit simplify translation from parameters to labels. It also removes a forgotten print.

Polish code in service backends_status

---

check_pgactivity

Fix backends

---

check_pgactivity

Typos in comments

---

CHANGELOG.md

Completed changelog to prepare release 2.3, for review.

Complete changelog for release 2.3

---

README
README.pod
check_pgactivity

This change will ensure that all services appears in alphabetical order in the documentation.

Reorder services in alphabetical order

---

check_pgactivity

exclude some apps for service oldest_idlexact

---

check_pgactivity

Remove a few trailing spaces

---

check_pgactivity

hit_ratio_uninitialized_ratio_bug

---

check_pgactivity

Fix max_nb_wal calculation in check_wal_files.

---

check_pgactivity

...as this service was not merged when I was adding all the comments about privileges

Add required privileges to uptime service comments

---

check_pgactivity

This commit only gives the opportunity to write PG11 specific queries.

Add initial support for PostgreSQL 11

---

CHANGELOG.md
check_pgactivity

This PR includes PR #207 and a patch by me fixing doc and supporting env variables.

Allow psql connections without any connection parameters given

---

check_pgactivity

Check errors during save() and load()

---

CHANGELOG.md
README
README.pod
RELEASING.md
check_pgactivity
check_pgactivity.spec

Updates, changelog, README.* for 2.4 release
Include doc update for RELEASING.md

WIP:Release 2.4

---

RELEASING.md

Some additional info that would have been useful in a first release.

Fix missing info in RELEASING.md

---

RELEASING.md

Fix typos in RELEASING.md

---

check_pgactivity

As seen in https://github.com/OPMDG/check_pgactivity/issues/226.

Add a checksum_errors service

---

check_pgactivity

This pull request tries to implement what has been discussed in issue #98.

Support delta & size thresholds for database_size

---

check_pgactivity

As of perfdata specs:
https://nagios-plugins.org/doc/guidelines.html#AEN200
Reported by Bas Gebbing on Github
Fix #227

Replace NaN with "U" for strict outputs

---

check_pgactivity

Allow replication_slots service on standby

---

check_pgactivity

Rename ok() & other to avoid conflict with Test modules

---

README
README.pod
check_pgactivity

Add version info & fix typo for invalid indexes

Add version info & fix typo for invalid indexes

---

README
README.pod
check_pgactivity

Microscopic update of comments on requirements.
Re-generation of `README`  and `README.pod`, to have an up-to-date doc when reading the Github page.

Minor doc update + README files

---

check_pgactivity

This is the whole result of my first regression tests with PG13 beta2.

PG 13 is coming

---

check_pgactivity

(Documentation) States that we won't add a parameter or passwords.

Issue #234 (doc): there is no parameter for a password

---

check_pgactivity

Do not alert lack of maintenance on inactive db

---

check_pgactivity

Ignore temp tables in maintenance services

---

check_pgactivity

Enhance check_sequences_exhaust to take account of all sequences

---

check_pgactivity

we want the oldest maintenance, so the max of the difference with
current_timestamp.

last_vacuum / last_analyze  s/min/max

---

check_pgactivity

We simply replace and fix the typo threshods_re -> thresholds_re.

Fix small typo into thresholds_re var name

---

check_pgactivity
t/01-archive_folder.t
t/01-archiver.t
t/01-autovacuum.t
t/01-backends.t
t/01-hit_ratio.t
t/01-idle_xact.t
t/01-last_analyze.t
t/01-streaming_delta.t
t/README
t/lib/PostgresNode.pm
t/lib/PostgresVersion.pm
t/lib/pgNode.pm
t/lib/pgSession.pm

Hello,
Here's a first test to ensure that idle_xact works as expected.
Kind regards

Add test harness for idlexact

---

check_pgactivity

Commit 0787397d69 removed lock_retrieve but I forgot dump_status_file and bin_output on the way.
Reported by Frédéric Yhuel, fix by me.

Remove forgotten lock_retrieve from 0787397d69

---

check_pgactivity

Fix check_archiver to work properly with PostgreSQL 10 without being superuser.
Fixes issues #333

Fix check_archiver

---

CHANGELOG.md
README
README.pod
check_pgactivity
check_pgactivity.spec
contributors
t/01-pga_version.t

Preparation work to release check_pga 2.7.
Please, review & comment.

Release 2.7

---

check_pgactivity

Declare PostgreSQL 16 and the upcoming release 17.

Add support for pg16 and pg17
