OPMDG/check_pgactivity

check_pgactivity

Use pg_statistic instead of pg_stats in order to do some table scans later in
the query plan.
Original patch by Ronan Dunklau, 7.4-8.1 adapted by me.

Optimize table_bloat queries

---

README.rst
check_pgactivity

_Add : table_unlogged service_
Check if table are changed to unlogged. In 9.5+, you can switch between logged and unlogged. This service track change and a critical alert is raised if an unlogged table is detected.

Add : table_unlogged service

---

check_pgactivity

The pg_stat_activity schema has changed again with PostgreSQL 9.6. The wait events monitoring adds some more complexity to monitor lock waits. This first attempt adds only a case for heavyweight locks to appears as sessions waiting for lock. The bufferpin and LWlock event types are not taken in account right now. We should probably add some new perfdata for those, but this will come later.

Add support for PostgreSQL 9.6 and fix backends_status

---

check_pgactivity

Apply the same fix to all other versions for consistency, but the problem does not seem to occur on other versions.

Fix a bug in the locks probe that occurs in PostgreSQL 8.2.

---

check_pgactivity

PostgreSQL 9.5 provides a function pg_stat_get_snapshot_timestamp() to provide the current statistics snapshot timestamp. This function can help to detect a stuck stats collector.

Add stat_snapshot_age to help monitor the current state of stats collector process.

---

check_pgactivity

This modification was forgotten as the version handling has been reworked.

Fix query_ver to work with PostgreSQL 10 and up

---

check_pgactivity

Hello,
Sorry, my query was wrong was I fixed backends_status for PostgreSQL 9.6 in commit edc4cf818f67a420d1c9104a6c8ace3ead1c0446. Waiting queries are not reported. This patch fixes this issue for heavyweight locks. There is still some room for improvement to support the new wait_event infrastructure, I hope to bring a better shaped patch next week.
Regards

Fix typo that prevents backends_status to report waiting backends from 9.6+

---

check_pgactivity

Min version was wrong in perldoc for check_stat_snapshot_age.

Fix stat_snapshot_age minversion in perldoc

---

check_pgactivity

Commit 806091c96f9b81f7631e4e37a05af377b473b5da in PostgreSQL source tree renamed all pg_*xlog* functions to pg_*wal* to remain consistent with the renaming of pg_xlog to pg_wal.

Another bunch of PostgreSQL 10 compatibility fixes

---

check_pgactivity

Commit 58a5303b9b78eb7025840f87ab003cf4da486f82 introduced support
for the new PostgreSQL wait event features from 9.6+. However it only
displayed heavyweight locks and didn't care about other wait event types.
This commit fixes this issue by introducing a new perfdata 'other wait event'
for check_backends_status.
A more complete patch may come later to count wait events more precisely.

Show wait events in check_backends_status

---

check_pgactivity

This probe returns perfdata with all wait events accounted.
For example :
```
$ ./check_pgactivity -h /tmp -p 5410 -U thomas -F human -s wait_events
Service        : POSTGRES_WAIT_EVENTS
Returns        : 0 (OK)
Perfdata       : Activity=0
Perfdata       : oldest_Activity=0s
Perfdata       : BufferPin=0
Perfdata       : oldest_BufferPin=0s
Perfdata       : Client=1
Perfdata       : oldest_Client=62.638s
Perfdata       : Extension=0
Perfdata       : oldest_Extension=0s
Perfdata       : IPC=0
Perfdata       : oldest_IPC=0s
Perfdata       : LWLock=0
Perfdata       : oldest_LWLock=0s
Perfdata       : Lock=1
Perfdata       : oldest_Lock=62.624s
Perfdata       : Timeout=0
Perfdata       : oldest_Timeout=0s
Perfdata       : total_wait_events=125.262
```

Add probe check_wait_events (9.6+)

---

README
README.pod
check_pgactivity

This bunch of commits take account of the new pg_monitor role in PostgreSQL 10.
Using this feature, we'll be able to use an unprivileged monitoring user. The following services were changed : 
* wal_files
* archiver
The btree_bloat and table_bloat services still works but one needs to grant the SELECT privilege on table pg_statistic to pg_monitor, inside each monitored databases, otherwise the check will fail. This is of course documented.
Also, one generic fix concerns the backends_status service. The query column was retrieved but was not used at all. Now this service simply retrieves actually used columns.

Some more PostgreSQL 10 fixes

---

check_pgactivity

As discussed in PR #89 , here the PR which add --exclude option available for streaming_delta service.
We can exclude every pattern we want from the sql result.

Add --exclude option in check_streaming_delta

---

check_pgactivity

Now we need to filter out the background processes from pg_stat_activity. The new column backend_type helps to do that.
Also fix a bug that made check_pgactivity wrongly report idle in xact backends in PostgreSQL 10.

In PostgreSQL 10, pg_stat_activity now shows the background processes too

---

check_pgactivity

Formerly, this probe could not emit a warning or critical for anything else
than for active or idle backends.

Fix long-standing bug in service backends_status

---

check_pgactivity

Some fixes to handle correctly string quoting and fix archiver that emitted a warning if archiver is desactived in PostgreSQL 10.

Various fixes

---

check_pgactivity

Added missing comment on the source of data for check_wal_files and PG>=9.5

Update comments for check_wal_files for PG >=9.5

---

check_pgactivity

The service temp_files monitors both live created temp files and get
its counters from pg_stat_database.
The live part is achieve through calls of the pg_ls_dir() function that
requires superuser privileges. As PostgreSQL 10 now brings the pg_monitor
role in order to help the user to monitor its db without superpowers.
This commit modifies the behaviour of temp_files in order to take
account of the live temp files if the user is superuser, or simply
skip this part if the monitoring user is a normal user.

Fix service temp_files to work with PostgreSQL 10

---

check_pgactivity

It was not clear from the doc that the postgres db and templates are never checked by some services : added a sentence for btree/table_bloat, invalid_indexes, last_analyze/vacuum, table_unlogged, sequences_exhausted

[Doc] Some services always exclude templates and the posgres database

---

check_pgactivity

For service table_unlogged :
- missing plural in output about excluded tables 
- "(9.5+)" missing in doc 
- changed formulation about --exclude REGEX in doc

table_unlogged: typo in error msg, add 9.5+ for doc

---

check_pgactivity

Symptom : ``POSTGRES_MINOR_VERSION UNKNOWN: Unknown major PostgreSQL version 10.0``
It fails both with and without the --critical switch. In both cases the x.y.z  structure is still hard coded to parse the RSS file or the threshold.
I've found no other way than making different tests if version is after or before 10.
Test:
After the 10.1 was released, the service on my 10.0 instance is critical. After the upgrade to 10.1, check_pga finds 10.1 correctly and returns OK again.
Tested with the RSS feed and the --critical parameters.
Tested on 9.6.5 instances and others which behave like before.
Does not recognize a 11devel version, and should not.
Includes small modifications that rjuju asked for.
(2nd PR as I've messed up the last rebase)

Minor version compatible with v10

---

check_pgactivity

archive_folder: added a line to make it clear that it must be executed on a server with access to the archive_folder, and this is not always the instance server.
Implicit mais ça va mieux en le disant.

archive_folder : doc update to clarify where to execute

---

check_pgactivity

Exclude options are ignored. It's usefull option if you want to exclude "ANALYZE" or "VACUUM" queries.
In current version "$r->[2]" is current_setting('max_connections'). Isn't query string.

Fix exclude option in backends_status service

---

check_pgactivity

check_pgactivity --service check_pga_version: avoid a warning when testing testing 2.4dev

Avoid warning for 2.4dev (service check_pga_version)

---

check_pgactivity

It seems that we missed the rename of location to lsn for this one.

Fix is_replay_paused for PostgreSQL 10

---

check_pgactivity

Adds informations at the end of comments, before the samples queries,
about required privileges of all services: unprivileged, pg_monitor,
superuser, ability to log in all databases, filesystem level needs...
Tested with Nagios users and PG roles with different levels, and I've tested many queries, mainly on v9.6 and 10.

Add privileges information for all services.

---

check_pgactivity

cf Issue #139 
Added a new service "uptime" whose main goal is graphing time since postmaster restart and configuration reload, in the same way as the classical uptime nagios service.   (I don't know if "uptime" is such a good name for the service, btw).
Tested on 8.2 (no conf load time available), 8.4, 9.1, 9.4, 9.6, 10
Critical and Warning thresholds are optional. If both are set, Critical is
raised when the postmaster uptime is less than the critical threshold, and
Warning is raised when the configuration uptime is less than the warning thereshold.
If only a warning or critical threshold is given, it will be used for both cases.
Obviously these alerts will disappear from themselves once enough time has passed. If the user do not want a mail to be sent, he'll put no threshold. 
Output …

uptime service

---

check_pgactivity

In case we encounter the startup state, we'll encounter 0/0 as current replication LSN,
meaning that we might a lag of hundreds of giga-bytes or tera-bytes.
Ignore such behavior but filtering out the startup state, as well as the backup state.

Ignore startup and backup replication states in service streaming_delta

---

check_pgactivity

Among others: missing or abusive plurals, reversed adjective/noun or adverb/verb
order, missing s on some verbs.
Harmonize imperative tense in the beginning of the description of the services.
Ending points.
Tried to reduce some sentences with useless verbs or words ("to use", "given"...);
use imperative to describe some options.
Uppercase on 1st letter in all comments
Minor version description was a bit confusing; reworked by putting the result
along the description of online/offline mode, and the parameter description afterwards.

Fix spelling, grammar, case... in the comments and documentation

---

check_pgactivity

WAL version in PostgreSQL code is : 
* 0xD093 in version 9.6
* 0xD097 in version 10
Thus in the check_pgactivity code : 
* 53395 in version 9.6
* 53399 in version 10

set correct version for wal magic number in version 10

---

check_pgactivity

This service support dbinclude/dbexclude, hits is not in the description

sequences_exhausted: missing comment on dbinclude/dbexclude support

---

check_pgactivity

Correct the header for the pod and man outputs. Man pages use a head1 level for NAME, SYNOPSIS... I've left head2 for EXAMPLES, SERVICES... 
Added the NAME section, that was missing. While building the Debian package, lintian was complaining about it.
I've tested this way:
```
perldoc -u check_pgactivity >README.pod 
pod2man --center "check_pgactivity" -r "Debian" --quotes=none --name=CHECK_PGACTIVITY  --section 1 README.pod > check_pgactivity.1  
man -l check_pgactivity.1 
```
README.pod and README are not updated, as I suppose that is part of the release process.

Correct head level for man pages

---

check_pgactivity

pg_ls_dir and other functions need a GRANT EXECUTE now.
pg_server_read_files seems useless for us.
Corrected comments for pgdata (superuser is necessary to see data_directory <v11)

 Updated doc on privileges for v11

---

check_pgactivity

Add wal_keep_segments when computing the max number of wal files to keep in v10.
See https://github.com/OPMDG/check_pgactivity/issues/194
(Bonus: a typo, a comment)

Fix wal_files: wal_keep_segments forgotten in v10

---

check_pgactivity

Hello,
Here is a patch which is imho a better step toward a clean solution for #155.
When a x30 or x03 appears in a result, it change the number of rows in a way or an other. This patch just checks that all rows in a result set has the same number of column, raisins an UNKNOWN with the error message if they diverge.
This solution is not perfect, it could be tricked by a value having the proper serie of x30 and x03, but I believe it's a cleaner way to mitigate the problem right now.

Mitigate gh issue #155

---

check_pgactivity

Modification of wal_files and replication_slots, as wal_segment_size is now stored as bytes, and not as blocks anymore.
Added a few comments to help the next one that will try to re-engineer this part.
Tested on a setup with 1 Go WAL files, it seems fine.
Wal_files assumes that #195 (bug #194) will be applied.

(v11 compatibility) wal_files and replications_slots

---

check_pgactivity

With archives like "0000000B000000000000005B" in the directory, we get the following error:
```
Argument "0000000B" isn't numeric in addition (+) at ./check_pgactivity line 1543.
```
Because it was handled as decimal, not hexadecimal.

handle archives timeline part as hexadecimal

---

CHANGELOG.md
check_pgactivity

Hi,
This PR contains:
- An example for replication_slot service
- A change for commit_ratio threshold from integer type to float. It may be useful when rollback_ratio is low (less than 1%), you can specify `rollback_ratio=0.1` for 0.1% rollback ratio.
- CHANGELOG.md updated for 2.4 release
I you prefer I can split this PR in separate PR for CHANGELOG.md vs other commits.
Regards,

Release 2.4 and other fix

---

check_pgactivity

After a crash and restart, the postmaster uptime stays the same although practically everything has restarted.
On PG10+, uptime is the age of the latest child process (usually checkpointer, writer...).
pg_monitor at least is needed. Client backends are excluded because some were met that were older although dead.
The same fix on PG 9.6 and before will need to find another way.

 Fix uptime failure to detect a crash-and-restart after a child process failure (10+)

---

check_pgactivity

Usage of 'pg_walfile_name()' is forbidden on standby. The fix makes the query
even more difficult to read, but we now parse the current LSN to compute the
number of WAL produced so far and compare with last archived one.
Fix #200

Fix archiver check on standby

---

check_pgactivity

Service pgdata_permission is broken since commit
82158b3ba242aa7bbc0cbcb4217444dd6bd61b44
This commit expects the first row to be the columns names and removes it from
final result. However, pgdata_permission doesn't expect query result, but
system command output using psql command \!, without header. So the system
command dresult was in fact removed as the header part, leaving no data to
parse to the pgdata_permission service...
If #155 is fixed at some point, don't forget to clean this on the way.

Ugly hack to fix regression in pgdata_permission

---

check_pgactivity

Added an exit when the query counting the sequences does not return any line.

Fix failure of sequences_exhausted on PG<10 when no sequence exist

---

check_pgactivity

The archiver check was not working with pgsql 10 and after. It was
not complaining when the archiver was failing, neither reporting
the number of waiting WAL to archive.
This fix #236 on github

Fix broken archiver service

---

check_pgactivity

Fix #238 
For v12 only, use the last version from ioguix's table bloat query.

Fix table bloat for v12: add last version from ioguix (v12 only)

---

check_pgactivity

- Added some documentation  (following https://github.com/OPMDG/check_pgactivity/pull/225#issuecomment-567008377)
- Added a fix for delta computing: percentage was made against the new database size, so `delta=150%` could not raise anything. Modified some variable names to avoid repeating the same mistake. IMHO we must leave a dprint there.

Database size : doc + fix delta 

---

check_pgactivity

- query PG_VERSION_100: background workers shouldnt count towards
client_backends. With this patch 'backend_type' is now restricted
to 'client backend' only since walsenders are accounted for using
pg_stat_replication.
- query PG_VERSION_120: the modification is the same here. Except that
the result of the query was correct because the backend_type
'background worker' doesn't exist anymore, it was replaced by 'logical
replication worker' and 'parallel worker' in version 11.

Fix backend count for PostgreSQL version 10 and a typo in 12.

---

check_pgactivity

In dark ancient ages, Perl didn't provide JSON::PP by default. This PR fixes issue #253.
Regards

Fix check_pga to run on prehistoric Perl installation

---

check_pgactivity

PostgreSQL 12 introduced function pg_ls_tmpdir to list live temp files
in a given tablespace. This function requires the pg_monitor privilege

Use pg_ls_tmpdir() in check_temp_files

---

check_pgactivity

Fixes issue #249.
The output of the probe may be changed as -infinity is returned by check_pgactivity when at least one table lacks maintenance.

Fix lack of maintenance detaction in check_last_maintenance

---

check_pgactivity

In the check_temp_files, since we are first getting file list before getting their size, some files could get missing in the meantime. The check then fails with the following error:
```
CHECK_PGACTIVITY UNKNOWN: Query failed !
psql:/tmp/check_pga-pBGcyGwB:29: ERROR:  could not stat file base/pgsql_tmp/pgsql_tmp25560.109: No such file or directory
```
Update the SQL query for versions 10+ to return a size of 0 for the missing files.

do not error on missing file in check_temp_files for version 10+

---

check_pgactivity

On PG13+, wal_keep_size replaces wal_keep_segments.
The logic stays the same, everything is computed as number of wals.
While testing, I found that a division by zero can occur. In this cas,e just disable the wal_rate in the perfdata.
I've played with the settings and it works as expected:

Wal_files on PG13 : wal_keep_segments (issue #266)

---

check_pgactivity

--path and --pattern are not always obvious in non trivial cases,
so I added an example with the date in the path.
I've put the 3 examples together after the path/patterns parameters.

  pg_dump_backups documentation: examples

---

check_pgactivity

Check all extensions installed in all databases
and raise an alarm if the current version is not the default version available
on the instance.
Typically, it is used to detect forgotten extension upgrades after package
upgrades or a pg_upgrade.

Add a new service called extensions_versions

---

check_pgactivity

See #270 
Added a compatiblity section at the top: psql client must be 8.3 and the server at least 7.4. It was not written elsewhere. As some services are flagged "all versions", the server minimal version could be discussed.

Minimal version 7.4, and psql client 8.3

---

check_pgactivity

This implements the check mentioned in https://github.com/OPMDG/check_pgactivity/issues/201.
I'm not extremely sure of the pg_stat_activity part.  The problems I can see are:
- as soon as eg. a transaction retains some xid, active queries started after will also look like they're retaining the same amount of transactions.  However, if t hose queries continue to run after the initial transaction is finished, they'll be the source of retention.  So it's quite hard to really identify what actually retains the xmin horizons from an aggregated view.  The query is already complex enough, so I'm not in favor of adding extra steps to try to be smarter about that.
- For pg_stat_activity, I'm not exactly sure if both backend_xmin *and* backend_xid can both be earlier than the other.  Minimal …

Add a new oldest_xmin check.

---

check_pgactivity

* bad wal_status now triggers warning or critical alert
* add ability to warn/crit when remaining safe bytes becomes low
for a slot
* fix: do not show number of spilled files for physical slots
closes #260

Support for v13 improvement on replication slots

---

check_pgactivity

This may be a surprise for some people upgrading to 2.5.

last_analyze|vacuum: a warning about NULL values in pg_stat_user_tables

---

check_pgactivity

The threshold check was not strict enough, giving '1d' was ok where
the doc says this check only support raw values. In consequence,
check_pgactivity was failling with eg.:
Argument '"2d" isn't numeric in numeric ge (>=)'
Worst, the check was returning "OK".
The fix supports interval as threshold value and fix the related tests.

Fix threshold check and support interval for check_stat_snapshot_age

---

check_pgactivity

Fix check_oldest_idlexact to use state_change instead of xact_start to
calculate the idle time. The previous behavior leads to warn for active
long transaction.

Fix check_oldest_idlexact to use state_change

---

check_pgactivity

There's no guarantee that the lock file exists when trying to load counters
from the status file: the lock file can be removed or simply not habe been
created when upgrading check_pgactivity from older versions.
Fix #326.

Make sure that the lock file before trying to flock it.

---

check_pgactivity

Previously, backends_status used xact_start to check if a transaction is waiting for a lock or is idle for a given amount of time. This leads to false positive alerts when a transaction becomes transciently idle.

Fix backends_status to use state_change for pg>=9.2

---

check_pgactivity

A typo was done in commit cb0e5f4.
Also, add documentation about required privileges.

Fix commit cb0e5f4

---

check_pgactivity
t/01-backends_status.t

Active backends with wait_event_type other then Active ou Client were not accounted as active.
Add a bit more debug output and a regression test for it.
Fix issue #345

Fix check_backends_status to simplify session accounting

---

check_pgactivity

This check aimed to detect a staled stats collector that happened sometimes before release 15. It's useless for pg 15+. This patch adds a check for this and updates the documentation (See #352).

stat_snapshot_age valid for 9.5 => 14

---

check_pgactivity
t/01-temp-files.t

Closes #350
Restore the filter on pgsql_tmp directory lost in the v10 adaptation,
which lead to wrong results when tablespaces are present.
The last pg_ls_dir is transformed as a OUTER JOIN LATERAL
to keep the line of tablespaces without lines, like in 9.6.
As a by product, pg_default is always listed as a tablespace again.
Before (with a running query, a few tablespaces):
```
$ /opt/check_pgactivity/check_pgactivity --status-file=/tmp/sdfdsf -s temp_files  --dbservice  nagios_defo10
POSTGRES_TEMP_FILES OK: 18 tablespace(s)/database(s) checked | '# files in test 2'=1File 'Total size in test 2'=0B '# files in untbl'=2300File 'Total size in untbl'=178224263B '# files in pg_default'=2File 'Total size in pg_default'=167377664B '# files in test'=1File 'Total size in test'=0B …
```

fix: temp_files on PG10-11 is counting data files as temp files

---

check_pgactivity

Add an error message if `--path` is a directory and not a path with wildcards.
(a mistake so easy and obvious that documenting is not enough).
Added 2 debug statements that were really missing for people trying to understand which files were found.

#355: pg_dump_backup : error if --path is a directory

---

README
README.pod
check_pgactivity
t/lib/pgNode.pm

Make possible to remove the -w argument using the --old-psql argument.
Fix #270

Support psql older than 8.4

---

check_pgactivity

When there is no write, the last_analyze and last_vacuum raised no alert when crossing the threshold. This is okay. But lowering the threshold did not lead to an alert.
Add the thresholds in the MD5 stored in the status file to force a new test when they change. That may lead to a new alert on totally inactive server when check_pgactivity is upgraded.
Close #325

(#325, last_maintnenance) Raise alerts on threshold change

---

check_pgactivity

Some walsender sessions emit a "START REPLICATION" query and are accounted as active queries, while there's no impact on the system and the replication is up and running.
Fixes issue #371

longest_query only account client backends, bgworkers and autovacuum workers

---

check_pgactivity
t/01-hugepages.t

PG17 added a guc `huge_page_status` to show the allocation state of huge pages when setting up a server with `huge_pages = try`. This MR add a service to check this guc cf (#296).
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=a14354cac

Adds the hugepages service
